CREATE USER mbwuser WITH PASSWORD 'mbwuser!';
GRANT ALL PRIVILEGES ON DATABASE mbwdatabase TO MBWUser;
GRANT ALL ON SCHEMA public TO MBWUser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO MBWUser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO MBWUser;