// <auto-generated />
using System;
using MBW.Server.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MBW.Server.Migrations
{
    [DbContext(typeof(MBDBContext))]
    [Migration("20260210140650_name")]
    partial class name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MBW.Server.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. Andy Dufresne, a banker wrongly convicted of murder, befriends fellow lifer Red while maintaining his innocence and dignity.",
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Length = 142,
                            ReleaseDate = new DateOnly(1994, 10, 14),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son. Michael Corleone is drawn deeper into the family business, transforming from war hero to ruthless mob boss in this epic tale of power, loyalty, and corruption.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            Length = 175,
                            ReleaseDate = new DateOnly(1972, 3, 24),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman faces the Joker in Gotham City as the Clown Prince of Crime unleashes chaos and forces the Dark Knight to confront his own moral limits. Heath Ledger delivers an unforgettable performance as the anarchic villain who seeks to prove that anyone can be corrupted.",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Length = 152,
                            ReleaseDate = new DateOnly(2008, 7, 18),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The life journey of a kind-hearted man with below-average intelligence who witnesses and influences several defining historical events in 20th century America. Despite his limitations, Forrest's genuine nature and unwavering love for Jenny carry him through an extraordinary life.",
                            Director = "Robert Zemeckis",
                            Genre = "Drama",
                            Length = 154,
                            ReleaseDate = new DateOnly(1994, 7, 6),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A skilled thief who enters dreams to steal corporate secrets is given the inverse task of planting an idea into the mind of a CEO. Dom Cobb must navigate multiple layers of dreams within dreams, where the laws of physics bend and time dilates, while confronting his own guilt-ridden subconscious.",
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Length = 148,
                            ReleaseDate = new DateOnly(2010, 7, 16),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A computer hacker discovers that reality as he knows it is actually a simulated construct created by sentient machines to pacify humanity while using their bodies as an energy source. Neo must choose between the comfortable lie of the Matrix and the harsh truth of the real world.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Genre = "Sci-Fi",
                            Length = 136,
                            ReleaseDate = new DateOnly(1999, 3, 31),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 7,
                            Description = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more dangerous. As the narrator becomes increasingly consumed by the violent subculture, his grip on reality begins to slip in this dark commentary on consumerism and masculinity.",
                            Director = "David Fincher",
                            Genre = "Drama",
                            Length = 139,
                            ReleaseDate = new DateOnly(1999, 10, 15),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A humble hobbit named Frodo Baggins inherits a powerful ring and must journey to Mount Doom to destroy it before the dark lord Sauron can reclaim it. He is joined by a fellowship of diverse heroes in this epic quest that will determine the fate of Middle-earth.",
                            Director = "Peter Jackson",
                            Genre = "Fantasy",
                            Length = 178,
                            ReleaseDate = new DateOnly(2001, 12, 19),
                            Title = "LOTR: Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The fellowship has been broken, and the quest continues on multiple fronts as Frodo and Sam press toward Mordor with the treacherous Gollum as their guide. Meanwhile, Aragorn, Legolas, and Gimli must defend the kingdom of Rohan against Saruman's massive orc army at Helm's Deep.",
                            Director = "Peter Jackson",
                            Genre = "Fantasy",
                            Length = 179,
                            ReleaseDate = new DateOnly(2002, 12, 18),
                            Title = "LOTR: The Two Towers"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The final battle for Middle-earth begins as Aragorn embraces his destiny as king, Gandalf leads the defense of Minas Tirith against Sauron's forces, and Frodo reaches the fires of Mount Doom. The culmination of the epic trilogy delivers emotional payoffs and spectacular warfare on an unprecedented scale.",
                            Director = "Peter Jackson",
                            Genre = "Fantasy",
                            Length = 201,
                            ReleaseDate = new DateOnly(2003, 12, 17),
                            Title = "LOTR: Return of the King"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dinosaurs are brought back to life through genetic engineering for an ambitious theme park, but the prehistoric creatures break free when the park's security systems fail. A paleontologist, paleobotanist, and mathematician must survive the island while protecting two young children from the rampaging dinosaurs.",
                            Director = "Steven Spielberg",
                            Genre = "Adventure",
                            Length = 127,
                            ReleaseDate = new DateOnly(1993, 6, 11),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A young farm boy named Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to rescue a rebel princess from the clutches of the evil Galactic Empire. His journey sets him on the path to becoming a legendary Jedi and ignites a galactic rebellion.",
                            Director = "George Lucas",
                            Genre = "Sci-Fi",
                            Length = 121,
                            ReleaseDate = new DateOnly(1977, 5, 25),
                            Title = "Star Wars: A New Hope"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The Empire launches a devastating attack on the Rebel Alliance, scattering the heroes across the galaxy. Luke seeks training from the ancient Jedi Master Yoda while Han and Leia evade Imperial forces, leading to shocking revelations about Luke's heritage and the true nature of the Force.",
                            Director = "Irvin Kershner",
                            Genre = "Sci-Fi",
                            Length = 124,
                            ReleaseDate = new DateOnly(1980, 5, 21),
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Luke Skywalker confronts Darth Vader in a final showdown before the Emperor while the Rebel Alliance launches a desperate attack on the second Death Star. The fate of the galaxy hangs in the balance as father and son face each other, and the dark side's hold on Anakin Skywalker is finally tested.",
                            Director = "Richard Marquand",
                            Genre = "Sci-Fi",
                            Length = 131,
                            ReleaseDate = new DateOnly(1983, 5, 25),
                            Title = "Return of the Jedi"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Toys come to life when humans aren't around, and cowboy doll Woody faces an existential crisis when a high-tech space ranger named Buzz Lightyear threatens his position as Andy's favorite toy. Their rivalry turns to friendship as they must work together to escape the clutches of the toy-torturing neighbor, Sid.",
                            Director = "John Lasseter",
                            Genre = "Animation",
                            Length = 81,
                            ReleaseDate = new DateOnly(1995, 11, 22),
                            Title = "Toy Story"
                        },
                        new
                        {
                            Id = 16,
                            Description = "An overprotective clownfish named Marlin embarks on a perilous journey across the ocean to find his son Nemo, who was captured by divers and taken to a dentist's aquarium in Sydney. Along the way, Marlin teams up with the forgetful but optimistic Dory in this heartwarming tale of parental love and letting go.",
                            Director = "Andrew Stanton",
                            Genre = "Animation",
                            Length = 101,
                            ReleaseDate = new DateOnly(2003, 5, 30),
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            Id = 17,
                            Description = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic. As Jack and Rose's forbidden romance blossoms during the ship's maiden voyage, tragedy strikes when the vessel collides with an iceberg, turning their love story into a desperate fight for survival.",
                            Director = "James Cameron",
                            Genre = "Romance",
                            Length = 195,
                            ReleaseDate = new DateOnly(1997, 12, 19),
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = 18,
                            Description = "With Earth becoming uninhabitable, a team of astronauts travels through a wormhole near Saturn in search of a new home for humanity. Former pilot Joseph Cooper must leave his children behind to explore distant galaxies where time behaves strangely, racing against the clock to save the human race.",
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Length = 169,
                            ReleaseDate = new DateOnly(2014, 11, 7),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 19,
                            Description = "The rise and fall of Henry Hill through the ranks of the mob is chronicled from his early days as a teenager running errands for mobsters to his eventual downfall. Based on a true story, this visceral portrait of organized crime depicts the glamorous lifestyle and brutal violence of the Italian-American mafia in New York.",
                            Director = "Martin Scorsese",
                            Genre = "Crime",
                            Length = 146,
                            ReleaseDate = new DateOnly(1990, 9, 12),
                            Title = "Goodfellas"
                        },
                        new
                        {
                            Id = 20,
                            Description = "FBI trainee Clarice Starling seeks the help of imprisoned cannibalistic serial killer Dr. Hannibal Lecter to catch another serial killer known as Buffalo Bill. As Clarice delves deeper into the twisted minds of psychopaths, she must face her own demons while racing against time to save Buffalo Bill's latest victim.",
                            Director = "Jonathan Demme",
                            Genre = "Thriller",
                            Length = 118,
                            ReleaseDate = new DateOnly(1991, 2, 14),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Following the D-Day invasion, a group of U.S. soldiers goes behind enemy lines during World War II on a dangerous mission to retrieve a paratrooper whose three brothers have been killed in action. Captain John Miller and his squad question the morality of risking eight men to save one in this brutal and realistic portrayal of war.",
                            Director = "Steven Spielberg",
                            Genre = "War",
                            Length = 169,
                            ReleaseDate = new DateOnly(1998, 7, 24),
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = 22,
                            Description = "A powerful Roman general named Maximus is betrayed and his family murdered by the corrupt son of the Emperor. Sold into slavery and forced to become a gladiator, Maximus rises through the ranks of the arena, seeking vengeance against the man who destroyed his life while the fate of Rome hangs in the balance.",
                            Director = "Ridley Scott",
                            Genre = "Action",
                            Length = 155,
                            ReleaseDate = new DateOnly(2000, 5, 5),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 23,
                            Description = "A teenager is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his eccentric scientist friend. Marty McFly must ensure his teenage parents fall in love in 1955 or risk erasing his own existence, all while finding a way back to 1985 in this perfect blend of comedy and science fiction.",
                            Director = "Robert Zemeckis",
                            Genre = "Sci-Fi",
                            Length = 116,
                            ReleaseDate = new DateOnly(1985, 7, 3),
                            Title = "Back to the Future"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Two detectives, a veteran and a rookie, hunt a serial killer who uses the seven deadly sins as his modus operandi. As Detective Somerset prepares for retirement and Detective Mills begins his career, they navigate a dark urban landscape pursuing a methodical killer whose crimes grow increasingly disturbing, leading to a devastating finale.",
                            Director = "David Fincher",
                            Genre = "Crime",
                            Length = 127,
                            ReleaseDate = new DateOnly(1995, 9, 22),
                            Title = "Se7en"
                        },
                        new
                        {
                            Id = 25,
                            Description = "An orphaned boy discovers on his eleventh birthday that he is actually a wizard and has been accepted to Hogwarts School of Witchcraft and Wizardry. Harry Potter learns about his famous past, makes lifelong friends, and confronts the dark wizard who murdered his parents in this magical adventure based on J.K. Rowling's beloved novel.",
                            Director = "Chris Columbus",
                            Genre = "Fantasy",
                            Length = 125,
                            ReleaseDate = new DateOnly(2001, 7, 20),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 26,
                            Description = "After the devastating events of Infinity War where Thanos eliminated half of all life in the universe, the remaining Avengers assemble one final time to undo the Mad Titan's actions. Through a dangerous time heist, Earth's mightiest heroes attempt to restore those they've lost in this epic conclusion to the Infinity Saga.",
                            Director = "Russo Brothers",
                            Genre = "Superhero",
                            Length = 181,
                            ReleaseDate = new DateOnly(2019, 4, 26),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Billionaire industrialist Tony Stark is captured by terrorists and forced to build a devastating weapon. Instead, he creates a high-tech suit of armor to escape captivity. Returning home, Stark refines his invention and transforms himself into the armored superhero Iron Man, launching the Marvel Cinematic Universe.",
                            Director = "Jon Favreau",
                            Genre = "Superhero",
                            Length = 126,
                            ReleaseDate = new DateOnly(2008, 6, 13),
                            Title = "Iron Man"
                        },
                        new
                        {
                            Id = 28,
                            Description = "A former Special Forces operative turned mercenary undergoes a rogue experiment that leaves him with accelerated healing powers and a twisted sense of humor. Wade Wilson adopts the alter ego Deadpool and hunts down the man who nearly destroyed his life, all while breaking the fourth wall in this irreverent superhero film.",
                            Director = "Tim Miller",
                            Genre = "Action",
                            Length = 108,
                            ReleaseDate = new DateOnly(2016, 2, 12),
                            Title = "Deadpool"
                        },
                        new
                        {
                            Id = 29,
                            Description = "In a near future where mutants are nearly extinct, an aging and weary Logan lives a quiet life caring for a dying Professor X. When a young mutant girl with abilities similar to his own appears, Logan must protect her from dark forces hunting her down in this emotional and violent conclusion to Wolverine's story.",
                            Director = "James Mangold",
                            Genre = "Action",
                            Length = 137,
                            ReleaseDate = new DateOnly(2017, 3, 3),
                            Title = "Logan"
                        },
                        new
                        {
                            Id = 30,
                            Description = "The story of American scientist J. Robert Oppenheimer and his role in developing the atomic bomb during World War II. This biographical thriller explores the moral implications of creating such devastating weapons, Oppenheimer's security clearance hearing, and the personal cost of being known as the father of the atomic bomb.",
                            Director = "Christopher Nolan",
                            Genre = "Biography",
                            Length = 114,
                            ReleaseDate = new DateOnly(2023, 7, 21),
                            Title = "Oppenheimer"
                        });
                });

            modelBuilder.Entity("MBW.Server.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "The Godfather sets the standard for crime dramas. Brando's performance is unforgettable.",
                            MovieId = 2,
                            Title = "A Masterpiece",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Every scene is perfectly crafted. This is cinema at its finest.",
                            MovieId = 2,
                            Title = "Timeless Classic",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Heath Ledger's Joker is one of the greatest villain performances ever captured on film.",
                            MovieId = 3,
                            Title = "Heath Ledger's Legacy",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This transcends the superhero genre. It's a crime thriller first, superhero movie second.",
                            MovieId = 3,
                            Title = "Best Superhero Movie",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Nolan created something truly special here. The tension never lets up.",
                            MovieId = 3,
                            Title = "Dark and Gripping",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Improves on Batman Begins in every way. Absolutely phenomenal.",
                            MovieId = 3,
                            Title = "Perfect Sequel",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 7,
                            Content = "This movie makes me cry every single time. Tom Hanks is perfect.",
                            MovieId = 4,
                            Title = "Emotional Journey",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 8,
                            Content = "So many quotable moments and beautiful life lessons throughout.",
                            MovieId = 4,
                            Title = "Life Lessons",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 9,
                            Content = "A beautiful story about perseverance and kindness.",
                            MovieId = 4,
                            Title = "Heartwarming",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Nolan at his best. The layers of dreams within dreams are brilliantly executed.",
                            MovieId = 5,
                            Title = "Mind-Bending Masterpiece",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 11,
                            Content = "I've seen this five times and still catch new details every viewing.",
                            MovieId = 5,
                            Title = "Rewatchability",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Still debating whether the top fell or not. Genius ambiguity.",
                            MovieId = 5,
                            Title = "That Ending Though",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 13,
                            Content = "The hallway fight scene alone is worth the price of admission.",
                            MovieId = 5,
                            Title = "Visual Spectacle",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 14,
                            Content = "The soundtrack perfectly complements the intensity of the film.",
                            MovieId = 5,
                            Title = "Hans Zimmer Score",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Changed action movies forever. The bullet-time effects were groundbreaking.",
                            MovieId = 6,
                            Title = "Revolutionary",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 16,
                            Content = "So much deeper than just an action film. Makes you question reality.",
                            MovieId = 6,
                            Title = "Philosophical Depth",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Watched it again recently and it's still as impressive as 1999.",
                            MovieId = 6,
                            Title = "Still Holds Up",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 18,
                            Content = "The twist still gets me even on rewatches. Fincher is a master.",
                            MovieId = 7,
                            Title = "Twisted and Brilliant",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 19,
                            Content = "The social commentary is even more relevant today than when it was released.",
                            MovieId = 7,
                            Title = "Commentary on Consumerism",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 20,
                            Content = "The start of an incredible journey. Peter Jackson brought Middle-earth to life.",
                            MovieId = 8,
                            Title = "Epic Beginning",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 21,
                            Content = "Tolkien would be proud. This is how you adapt a beloved book.",
                            MovieId = 8,
                            Title = "Perfect Adaptation",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 22,
                            Content = "The casting is absolutely perfect. Every character feels authentic.",
                            MovieId = 8,
                            Title = "The Fellowship",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 23,
                            Content = "The soundtrack is hauntingly beautiful and elevates every scene.",
                            MovieId = 8,
                            Title = "Howard Shore's Music",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 24,
                            Content = "The Battle of Helm's Deep is one of the greatest battle sequences ever filmed.",
                            MovieId = 9,
                            Title = "Helm's Deep",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Andy Serkis deserved an Oscar. Gollum is incredibly realistic and tragic.",
                            MovieId = 9,
                            Title = "Gollum's Performance",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 26,
                            Content = "The ending had me in tears. What a way to finish the trilogy.",
                            MovieId = 10,
                            Title = "Perfect Conclusion",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 27,
                            Content = "Swept the Academy Awards and deserved every single one.",
                            MovieId = 10,
                            Title = "11 Oscars!",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 28,
                            Content = "The Battle of Pelennor Fields is breathtaking in scope and execution.",
                            MovieId = 10,
                            Title = "Epic Scale",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 29,
                            Content = "After three films, seeing everyone's journey conclude is so satisfying.",
                            MovieId = 10,
                            Title = "Emotional Payoff",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 30,
                            Content = "While all three are masterpieces, this one edges out the others for me.",
                            MovieId = 10,
                            Title = "Best of the Trilogy",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 31,
                            Content = "This movie made me fall in love with dinosaurs. Still magical today.",
                            MovieId = 11,
                            Title = "Childhood Favorite",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 32,
                            Content = "The T-Rex escape scene is pure cinematic perfection.",
                            MovieId = 11,
                            Title = "Spielberg Magic",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 33,
                            Content = "The mix of animatronics and CGI still looks better than many modern films.",
                            MovieId = 11,
                            Title = "Practical Effects",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 34,
                            Content = "Changed cinema forever. The beginning of an incredible saga.",
                            MovieId = 12,
                            Title = "Started It All",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 35,
                            Content = "Han, Luke, Leia - these characters defined a generation.",
                            MovieId = 12,
                            Title = "Iconic Characters",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 36,
                            Content = "Lucas created such a rich and detailed universe. Amazing vision.",
                            MovieId = 12,
                            Title = "World-Building",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 37,
                            Content = "The mythology and philosophy behind the Force is fascinating.",
                            MovieId = 12,
                            Title = "The Force",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 38,
                            Content = "Darker, more complex, and emotionally resonant. The peak of the saga.",
                            MovieId = 13,
                            Title = "Best Star Wars Film",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 39,
                            Content = "One of the greatest plot twists in cinema history. Still gives me chills.",
                            MovieId = 13,
                            Title = "I Am Your Father",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 40,
                            Content = "The Dagobah scenes with Yoda are the heart of this film.",
                            MovieId = 13,
                            Title = "Yoda's Wisdom",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 41,
                            Content = "The redemption of Vader makes the entire original trilogy worthwhile.",
                            MovieId = 14,
                            Title = "Satisfying Ending",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 42,
                            Content = "Say what you will, but the Ewoks are adorable and fun.",
                            MovieId = 14,
                            Title = "Ewoks!",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 43,
                            Content = "The film that launched Pixar's incredible run. Revolutionary animation.",
                            MovieId = 15,
                            Title = "Pixar's First",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 44,
                            Content = "Not just a kids movie. The themes of friendship and jealousy are universal.",
                            MovieId = 15,
                            Title = "Adults Love It Too",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 45,
                            Content = "My kids love this just as much as I did when it came out.",
                            MovieId = 15,
                            Title = "Timeless Story",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 46,
                            Content = "The ocean environments are gorgeously rendered. Pixar outdid themselves.",
                            MovieId = 16,
                            Title = "Beautiful Underwater World",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 47,
                            Content = "The relationship between Marlin and Nemo is so touching.",
                            MovieId = 16,
                            Title = "Father-Son Story",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 48,
                            Content = "Jack and Rose's love story still makes me cry. Cameron's masterpiece.",
                            MovieId = 17,
                            Title = "Epic Romance",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 49,
                            Content = "The attention to detail in recreating the ship is incredible.",
                            MovieId = 17,
                            Title = "Historical Accuracy",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 50,
                            Content = "My Heart Will Go On is forever tied to this film. Iconic.",
                            MovieId = 17,
                            Title = "Celine Dion",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 51,
                            Content = "The second half is intense and heartbreaking. Amazingly done.",
                            MovieId = 17,
                            Title = "The Sinking",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 52,
                            Content = "Nolan's most ambitious film. The scale is mind-boggling.",
                            MovieId = 18,
                            Title = "Space Epic",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 53,
                            Content = "The father-daughter relationship gives the sci-fi real heart.",
                            MovieId = 18,
                            Title = "Emotional Core",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 54,
                            Content = "Kip Thorne's involvement shows. The black hole visualization is scientifically grounded.",
                            MovieId = 18,
                            Title = "Scientific Accuracy",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 55,
                            Content = "The tension during the docking sequence had me holding my breath.",
                            MovieId = 18,
                            Title = "That Docking Scene",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 56,
                            Content = "Hans Zimmer creates another unforgettable soundtrack. The organ is perfect.",
                            MovieId = 18,
                            Title = "Zimmer's Score Again",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 57,
                            Content = "Peak Scorsese. The energy and pacing are unmatched.",
                            MovieId = 19,
                            Title = "Scorsese's Best",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 58,
                            Content = "Liotta's narration pulls you into the mob life. Fantastic performance.",
                            MovieId = 19,
                            Title = "Ray Liotta",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 59,
                            Content = "The Copacabana scene is one continuous shot of brilliance.",
                            MovieId = 19,
                            Title = "That Tracking Shot",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 60,
                            Content = "Anthony Hopkins makes Hannibal Lecter unforgettable with minimal screen time.",
                            MovieId = 20,
                            Title = "Hopkins is Terrifying",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 61,
                            Content = "The tension between Clarice and Lecter is electric. Masterful direction.",
                            MovieId = 20,
                            Title = "Psychological Thriller",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 62,
                            Content = "The D-Day landing is the most realistic war sequence ever filmed. Brutal and powerful.",
                            MovieId = 21,
                            Title = "Opening Scene",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 63,
                            Content = "This changed how war films are made. Unflinching and honest.",
                            MovieId = 21,
                            Title = "Spielberg's War Film",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 64,
                            Content = "Every soldier feels like a real person with a story. Great casting.",
                            MovieId = 21,
                            Title = "Ensemble Cast",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 65,
                            Content = "The ending gets me every time. Earn this.",
                            MovieId = 21,
                            Title = "Emotional Sacrifice",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 66,
                            Content = "Crowe commands the screen. One of the best action performances.",
                            MovieId = 22,
                            Title = "Are You Not Entertained?",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 67,
                            Content = "Ridley Scott brings ancient Rome to life. The Colosseum battles are incredible.",
                            MovieId = 22,
                            Title = "Roman Spectacle",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 68,
                            Content = "Maximus' journey from general to slave to gladiator is gripping.",
                            MovieId = 22,
                            Title = "Revenge Story",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 69,
                            Content = "One of the most fun movies ever made. Never gets old.",
                            MovieId = 23,
                            Title = "Perfect Entertainment",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 70,
                            Content = "The paradoxes and timeline are handled brilliantly. Smart and funny.",
                            MovieId = 23,
                            Title = "Time Travel Done Right",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 71,
                            Content = "Fincher's vision is so bleak and captivating. The atmosphere is oppressive.",
                            MovieId = 24,
                            Title = "Dark Masterpiece",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 72,
                            Content = "The ending is devastating. One of cinema's darkest conclusions.",
                            MovieId = 24,
                            Title = "What's in the Box?",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 73,
                            Content = "The chemistry between the two leads drives the film. Perfect casting.",
                            MovieId = 24,
                            Title = "Pitt and Freeman",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 74,
                            Content = "The perfect introduction to the wizarding world. Captured the magic of the books.",
                            MovieId = 25,
                            Title = "Magical Beginning",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 75,
                            Content = "Seeing Hogwarts for the first time was pure magic. Columbus nailed it.",
                            MovieId = 25,
                            Title = "Childhood Wonder",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 76,
                            Content = "Daniel, Emma, and Rupert were perfectly cast. They grew up with these roles.",
                            MovieId = 25,
                            Title = "The Trio",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 77,
                            Content = "Hedwig's Theme is iconic. Williams created magic with the music.",
                            MovieId = 25,
                            Title = "John Williams",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 78,
                            Content = "The culmination of 22 films. The Russo Brothers stuck the landing.",
                            MovieId = 26,
                            Title = "Epic Conclusion",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 79,
                            Content = "That portals scene gave me chills. Pure comic book joy brought to life.",
                            MovieId = 26,
                            Title = "Avengers Assemble",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 80,
                            Content = "Tony's sacrifice had the entire theater in tears. I love you 3000.",
                            MovieId = 26,
                            Title = "Emotional Goodbye",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 81,
                            Content = "Revisiting past MCU moments was brilliant fan service done right.",
                            MovieId = 26,
                            Title = "Time Heist",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 82,
                            Content = "Didn't feel like three hours. Every minute earned its place.",
                            MovieId = 26,
                            Title = "Three Hour Epic",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 83,
                            Content = "RDJ was born to play Tony Stark. This launched everything.",
                            MovieId = 27,
                            Title = "Started the MCU",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 84,
                            Content = "The Mark I suit built in a cave is still one of my favorite sequences.",
                            MovieId = 27,
                            Title = "Practical Suit",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 85,
                            Content = "That ending changed superhero movies forever. No secret identity.",
                            MovieId = 27,
                            Title = "I Am Iron Man",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 86,
                            Content = "Finally a faithful Deadpool. Reynolds fought for this and it shows.",
                            MovieId = 28,
                            Title = "R-Rated Perfection",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 87,
                            Content = "The meta humor is perfectly balanced. Hilarious from start to finish.",
                            MovieId = 28,
                            Title = "Fourth Wall Breaking",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 88,
                            Content = "Hugh Jackman's final performance as Logan is heartbreaking and perfect.",
                            MovieId = 29,
                            Title = "Wolverine's Swan Song",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 89,
                            Content = "Mangold crafted something unique. Feels like a Western first, superhero film second.",
                            MovieId = 29,
                            Title = "Western Superhero Film",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 90,
                            Content = "The R-rating allows the violence and emotion to hit harder. Raw and real.",
                            MovieId = 29,
                            Title = "Dark and Brutal",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 91,
                            Content = "Dafne Keen steals scenes. The relationship between Logan and Laura is beautiful.",
                            MovieId = 29,
                            Title = "Laura",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 92,
                            Content = "A three-hour character study that never drags. Nolan's most mature film.",
                            MovieId = 30,
                            Title = "Nolan's Masterwork",
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 93,
                            Content = "Murphy finally gets the lead role he deserves. His Oppenheimer is haunting.",
                            MovieId = 30,
                            Title = "Cillian Murphy",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 94,
                            Content = "Nolan created the Trinity test without CGI. The commitment to practical filmmaking is admirable.",
                            MovieId = 30,
                            Title = "Practical Effects",
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 95,
                            Content = "The exploration of Oppenheimer's legacy and guilt is fascinating and relevant.",
                            MovieId = 30,
                            Title = "Historical Drama",
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 96,
                            Content = "This film demands to be seen in IMAX. The visuals and sound are overwhelming.",
                            MovieId = 30,
                            Title = "IMAX Experience",
                            Username = "testuser3"
                        });
                });

            modelBuilder.Entity("MBW.Server.Models.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParentPostId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Replies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Absolutely agree. The character development is masterful.",
                            ParentPostId = 1,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The opening scene sets the tone perfectly.",
                            ParentPostId = 1,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Have you seen the director's cut? Even better.",
                            ParentPostId = 1,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 4,
                            Content = "The cinematography is stunning throughout.",
                            ParentPostId = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 5,
                            Content = "His commitment to the role was incredible. RIP.",
                            ParentPostId = 3,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "The interrogation scene is pure acting brilliance.",
                            ParentPostId = 3,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 7,
                            Content = "He disappeared into that role completely.",
                            ParentPostId = 3,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 8,
                            Content = "The moral complexity elevates it above typical superhero fare.",
                            ParentPostId = 5,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 9,
                            Content = "The bench scenes with Jenny break my heart.",
                            ParentPostId = 7,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Hanks deserved every award for this performance.",
                            ParentPostId = 7,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Life is like a box of chocolates...",
                            ParentPostId = 7,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Run, Forrest, run! Never gets old.",
                            ParentPostId = 8,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 13,
                            Content = "The architecture of dreams is fascinating.",
                            ParentPostId = 10,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Each layer adds another dimension to the story.",
                            ParentPostId = 10,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 15,
                            Content = "The van sequence with different time scales is genius.",
                            ParentPostId = 10,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 16,
                            Content = "I choose to believe it keeps spinning.",
                            ParentPostId = 12,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 17,
                            Content = "The BRAAAM sound became iconic.",
                            ParentPostId = 14,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Time by Hans Zimmer is incredible.",
                            ParentPostId = 14,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Zimmer and Nolan are a perfect pairing.",
                            ParentPostId = 14,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 20,
                            Content = "The slow-mo sequences were mind-blowing in 1999.",
                            ParentPostId = 15,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 21,
                            Content = "The effects still look great today.",
                            ParentPostId = 17,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 22,
                            Content = "I watch it every few years and it never disappoints.",
                            ParentPostId = 17,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 23,
                            Content = "The green tint aesthetic is so iconic.",
                            ParentPostId = 17,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 24,
                            Content = "The reveal is so well-constructed.",
                            ParentPostId = 18,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 25,
                            Content = "The Shire looks exactly as I imagined reading the books.",
                            ParentPostId = 20,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 26,
                            Content = "The practical effects and sets are incredible.",
                            ParentPostId = 20,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 27,
                            Content = "New Zealand never looked so beautiful.",
                            ParentPostId = 20,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 28,
                            Content = "Ian McKellen and Viggo Mortensen are standouts.",
                            ParentPostId = 22,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 29,
                            Content = "The practical effects for that battle are astounding.",
                            ParentPostId = 24,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 30,
                            Content = "The siege towers and ladders felt so real.",
                            ParentPostId = 24,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 31,
                            Content = "Theoden's speech still gives me goosebumps.",
                            ParentPostId = 24,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 32,
                            Content = "I wasn't ready for that many endings, but all were necessary.",
                            ParentPostId = 26,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Tied with Ben-Hur and Titanic. Legendary.",
                            ParentPostId = 27,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 34,
                            Content = "Best Picture was well-deserved.",
                            ParentPostId = 27,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 35,
                            Content = "A clean sweep at the Oscars is so rare.",
                            ParentPostId = 27,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 36,
                            Content = "The Grey Havens scene destroys me every time.",
                            ParentPostId = 29,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 37,
                            Content = "The T-Rex reveal with the water ripples is iconic.",
                            ParentPostId = 31,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 38,
                            Content = "This sparked my interest in paleontology.",
                            ParentPostId = 31,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 39,
                            Content = "Welcome to Jurassic Park - chills!",
                            ParentPostId = 31,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 40,
                            Content = "The combination was revolutionary for the time.",
                            ParentPostId = 33,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 41,
                            Content = "The cultural impact cannot be overstated.",
                            ParentPostId = 34,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 42,
                            Content = "It created modern blockbuster filmmaking.",
                            ParentPostId = 34,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 43,
                            Content = "May the Force be with you - timeless.",
                            ParentPostId = 34,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 44,
                            Content = "The cantina scene alone shows the depth of the universe.",
                            ParentPostId = 36,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 45,
                            Content = "Kershner brought a different tone that elevated it.",
                            ParentPostId = 38,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 46,
                            Content = "The Hoth battle is incredible.",
                            ParentPostId = 38,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 47,
                            Content = "Cloud City is such a great setting.",
                            ParentPostId = 38,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 48,
                            Content = "No one saw it coming. Perfect execution.",
                            ParentPostId = 39,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 49,
                            Content = "The throne room confrontation is powerful.",
                            ParentPostId = 41,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 50,
                            Content = "Vader's turn back to the light is earned.",
                            ParentPostId = 41,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 51,
                            Content = "I never cry at movies, but that scene gets me.",
                            ParentPostId = 41,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 52,
                            Content = "Who knew CGI could be this charming?",
                            ParentPostId = 43,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 53,
                            Content = "Randy Newman's music is perfect.",
                            ParentPostId = 45,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 54,
                            Content = "You've Got a Friend in Me makes me nostalgic.",
                            ParentPostId = 45,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 55,
                            Content = "Watching it with kids adds a new dimension.",
                            ParentPostId = 45,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 56,
                            Content = "Just keep swimming! That mantra helped me through tough times.",
                            ParentPostId = 47,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 57,
                            Content = "DiCaprio and Winslet have incredible chemistry.",
                            ParentPostId = 48,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 58,
                            Content = "I'll never let go, Jack - devastating.",
                            ParentPostId = 48,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 59,
                            Content = "The king of the world scene is iconic.",
                            ParentPostId = 48,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 60,
                            Content = "That song will forever be associated with this film.",
                            ParentPostId = 50,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 61,
                            Content = "The visuals are stunning on IMAX.",
                            ParentPostId = 52,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 62,
                            Content = "Miller's planet with the time dilation is terrifying.",
                            ParentPostId = 52,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 63,
                            Content = "The wormhole scene is visually incredible.",
                            ParentPostId = 52,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 64,
                            Content = "The tesseract scene bends my mind.",
                            ParentPostId = 54,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 65,
                            Content = "No Time for Caution during the docking is perfection.",
                            ParentPostId = 56,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 66,
                            Content = "The organ creates such an otherworldly feel.",
                            ParentPostId = 56,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 67,
                            Content = "Zimmer outdid himself with this score.",
                            ParentPostId = 56,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 68,
                            Content = "The editing and pacing are masterful.",
                            ParentPostId = 57,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 69,
                            Content = "That shot is studied in film schools.",
                            ParentPostId = 59,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 70,
                            Content = "The precision required for that is insane.",
                            ParentPostId = 59,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 71,
                            Content = "Pure cinema magic in one take.",
                            ParentPostId = 59,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 72,
                            Content = "The fava beans line is chilling.",
                            ParentPostId = 60,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 73,
                            Content = "Changed my understanding of WWII films.",
                            ParentPostId = 62,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 74,
                            Content = "The sound design makes you feel like you're there.",
                            ParentPostId = 62,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 75,
                            Content = "I had to pause and collect myself after that scene.",
                            ParentPostId = 62,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 76,
                            Content = "Tom Hanks leads an incredible cast.",
                            ParentPostId = 64,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 77,
                            Content = "My name is Maximus Decimus Meridius...",
                            ParentPostId = 66,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 78,
                            Content = "Crowe's intensity is palpable in every scene.",
                            ParentPostId = 66,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 79,
                            Content = "The physicality he brought to the role was impressive.",
                            ParentPostId = 66,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 80,
                            Content = "The fallen leaves at the beginning foreshadow his journey.",
                            ParentPostId = 68,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 81,
                            Content = "The clockwork precision of the plot is remarkable.",
                            ParentPostId = 70,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 82,
                            Content = "Every rewatch reveals new details.",
                            ParentPostId = 70,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 83,
                            Content = "The screenplay is tight and clever.",
                            ParentPostId = 70,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 84,
                            Content = "The rain-soaked aesthetic is perfect.",
                            ParentPostId = 71,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 85,
                            Content = "That final scene haunts me.",
                            ParentPostId = 72,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 86,
                            Content = "Brad Pitt's reaction is so raw.",
                            ParentPostId = 72,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 87,
                            Content = "Ernest Hemingway said it best in the film.",
                            ParentPostId = 72,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 88,
                            Content = "Seeing the Great Hall for the first time was magical.",
                            ParentPostId = 74,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 89,
                            Content = "Watching them grow up on screen was special.",
                            ParentPostId = 76,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 90,
                            Content = "They embodied their characters perfectly.",
                            ParentPostId = 76,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 91,
                            Content = "The trio's friendship feels genuine.",
                            ParentPostId = 76,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 92,
                            Content = "11 years of storytelling paid off beautifully.",
                            ParentPostId = 78,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 93,
                            Content = "I stood up in the theater. Couldn't help myself.",
                            ParentPostId = 79,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 94,
                            Content = "That moment justified every previous film.",
                            ParentPostId = 79,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 95,
                            Content = "On your left - perfect callback.",
                            ParentPostId = 79,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 96,
                            Content = "RDJ gave everything to that role.",
                            ParentPostId = 80,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 97,
                            Content = "Not a wasted moment in the entire runtime.",
                            ParentPostId = 82,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 98,
                            Content = "The pacing is masterful.",
                            ParentPostId = 82,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 99,
                            Content = "I could watch another hour easily.",
                            ParentPostId = 82,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 100,
                            Content = "No one else could have played Tony Stark.",
                            ParentPostId = 83,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 101,
                            Content = "That press conference was a game-changer.",
                            ParentPostId = 85,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 102,
                            Content = "The public identity made MCU unique.",
                            ParentPostId = 85,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 103,
                            Content = "RDJ ad-libbed that line. Perfect.",
                            ParentPostId = 85,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 104,
                            Content = "The opening credits scene is genius.",
                            ParentPostId = 87,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 105,
                            Content = "17 years as Wolverine. What a legacy.",
                            ParentPostId = 88,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 106,
                            Content = "The rawness of his performance is stunning.",
                            ParentPostId = 88,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 107,
                            Content = "He went out on the highest note possible.",
                            ParentPostId = 88,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 108,
                            Content = "Finally showing what Wolverine can really do.",
                            ParentPostId = 90,
                            Username = "testuser3"
                        },
                        new
                        {
                            Id = 109,
                            Content = "The structure with three timelines is brilliant.",
                            ParentPostId = 92,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 110,
                            Content = "The black and white sequences are powerful.",
                            ParentPostId = 92,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 111,
                            Content = "Nolan's restraint makes it more impactful.",
                            ParentPostId = 92,
                            Username = "testuser2"
                        },
                        new
                        {
                            Id = 112,
                            Content = "The commitment to in-camera effects is admirable.",
                            ParentPostId = 94,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 113,
                            Content = "The sound design in IMAX is overwhelming.",
                            ParentPostId = 96,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 114,
                            Content = "70mm film makes such a difference.",
                            ParentPostId = 96,
                            Username = "testuser1"
                        },
                        new
                        {
                            Id = 115,
                            Content = "This is Nolan's most IMAX-worthy film.",
                            ParentPostId = 96,
                            Username = "testuser2"
                        });
                });

            modelBuilder.Entity("MBW.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hash = "f+sMn7oo7y6hh5wWoFvHwWIAAG07t07OUNEl5BQq8Q30FkVUdC6K40tLpVauz7jWBnlHwtphR6+/KwUmqTWbSw==",
                            Name = "admin",
                            Role = "ADMIN",
                            Salt = "kFaXeaDXHPtNRDPZd517LfrKlf6omU7XZ4E7lCxjFSDJLFhcgS+CV35kxMAJRGUxhRyAnGp9z676NK5Q7PQHYIV5lbYkrZ5X08CsF9ncRWQ8BoQaH4rTHmPrjtfCDzQF0HywBPGMbzsHqLBEDs3pCv+Bh9pt+7JAYg0RaH2QQA8="
                        },
                        new
                        {
                            Id = 2,
                            Hash = "Z9/FAsGUmTudmYKgEPaD4XLHnboaNWWAdHITiUN+/C4cIRsjTfpAw33hdKApFdS6gUAU9fhzIqNsr3k9cHJqaQ==",
                            Name = "testuser1",
                            Role = "AUTHENTICATEDUSER",
                            Salt = "2pJ8FMxMKYxuX6Wqsl5pXO2hh6HkHVXgW5TFFofNWQuwnENOYmXJG6aTUQDauKej+DDdx0JLI+QFwHWzQsUpetoR1+RBke0iAST3PuXjoovNerNdKqSBmxHOv4RzMMgVOV+D2pTIZxFgwmxFMRKTfj1xJPYBiDHFxftzPT+2ZtQ="
                        },
                        new
                        {
                            Id = 3,
                            Hash = "TZb0yh2zN0xpqAqDFThoIwgoPLWhMrReKrRerEMmmLlByEWcwdd+tPwxebveCPhsAG7ImPm7gYdykROrKwruGw==",
                            Name = "testuser2",
                            Role = "AUTHENTICATEDUSER",
                            Salt = "ihJ5oN69oDLnSLVM4nMdAtfafKXeCTMT3+sYQHy1gi8z/XNwGM3ogE9kbeFZfZf91KMvqt+FDgtvhp0+T686Z74TeYA795VYxi7y72nTbceFBqBYiPzznh0udgzGz5eJRvW8ukF4tXHtK2ViIbydw3DGxthzUm2hcwK1N/xaHx4="
                        },
                        new
                        {
                            Id = 4,
                            Hash = "LHlz0gscyF/ap2Ev0Ffzr2hxg0aVzqym7GFflmbvU9kQ02dfpqcjy2wyUtZebPOYaSxYK2S7UivHukKqYDwYcw==",
                            Name = "testuser3",
                            Role = "AUTHENTICATEDUSER",
                            Salt = "2QpGjfuIGtUBxUNAvpBJfaoQA8RHqSpq4PlyyfVkUbtauvcjI7E07ZckIbvjI9lMYqox/5VQDM3gTMKL5v07EVEF2RK09zcEuGyAzkpLldGd+ENDSjBImSWMMg6TMBvAHfBfzghe4+G4laKa7U3646seoawMnpoXLj2qHMSGT08="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
